export const bachelorDiplomaDict: {[key: number]: any} = {
    1: {"fag": "Det mindre projekt: Interaktionsdesign", "semester": 1, "karakter": "B", "ectsPoint": 5},
    2: {"fag": "Det større projekt: Evaluering af design", "semester": 1, "karakter": "10", "ectsPoint": 10},
    3: {"fag": "Usability og skitsering", "semester": 1, "karakter": "7", "ectsPoint": 5},
    4: {"fag": "Grundlæggende programmering", "semester": 1, "karakter": "12", "ectsPoint": 5},
    5: {"fag": "Problembaseret læring", "semester": 1, "karakter": "B", "ectsPoint": 5},
    6: {"fag": "Design og konstruktion af en webapplikation", "semester": 2, "karakter": "7", "ectsPoint": 15},
    7: {"fag": "Funktionelt og grafisk design", "semester": 2, "karakter": "10", "ectsPoint": 5},
    8: {"fag": "Anvendt grundlæggende programmering", "semester": 2, "karakter": "10", "ectsPoint": 5},
    9: {"fag": "Datalogiens matematiske grundlag", "semester": 2, "karakter": "7", "ectsPoint": 5},
    10: {"fag": "Design med brugere", "semester": 3, "karakter": "4", "ectsPoint": 15},
    11: {"fag": "Brugercentreret design", "semester": 3, "karakter": "10", "ectsPoint": 5},
    12: {"fag": "Databaseudvikling", "semester": 3, "karakter": "4", "ectsPoint": 5},
    13: {"fag": "Grundlæggende objektorienteret programmering", "semester": 3, "karakter": "10", "ectsPoint": 5},
    14: {"fag": "Interaktivt mobilt applikationsdesign", "semester": 4, "karakter": "12", "ectsPoint": 15},
    15: {"fag": "Interaktivt fysisk design", "semester": 4, "karakter": "B", "ectsPoint": 5},
    16: {"fag": "Kvalitativ metode", "semester": 4, "karakter": "7", "ectsPoint": 5},
    17: {"fag": "Programmering af mobile applikationer", "semester": 4, "karakter": "B", "ectsPoint": 5},
    18: {"fag": "Design af interaktion med data", "semester": 5, "karakter": "10", "ectsPoint": 15},
    19: {"fag": "Brugercentreret interaktion med kunstig intelligens", "semester": 5, "karakter": "7", "ectsPoint": 5},
    20: {"fag": "Kvantitativ metode", "semester": 5, "karakter": "B", "ectsPoint": 5},
    21: {"fag": "Systemanalyse og design", "semester": 5, "karakter": "7", "ectsPoint": 5},
    22: {"fag": "Bachelorprojekt", "semester": 6, "karakter": "10", "ectsPoint": 20},
    23: {"fag": "User Experience", "semester": 6, "karakter": "7", "ectsPoint": 5},
    24: {"fag": "Programmering af IoT applikationer", "semester": 6, "karakter": "10", "ectsPoint": 5},
}