export const highSchoolDiplomaDict: {[key: number]: any} = {
    1: {"n": 3,"fag": "Dansk", "niveau": "A", "type": "mdt.", "årsVægt": 1, "årsKarakter": 7, "prøveVægt": null, "prøveKarakter": null},
    2: {"n": 3,"fag": "Dansk", "niveau": "A", "type": "skr.", "årsVægt": 1, "årsKarakter": 7, "prøveVægt": 1, "prøveKarakter": 7},
    3: {"n": 3,"fag": "Fysik", "niveau": "A", "type": "mdt.", "årsVægt": 1, "årsKarakter": 10, "prøveVægt": null, "prøveKarakter": null},
    4: {"n": 3,"fag": "Fysik", "niveau": "A", "type": "skr.", "årsVægt": 1, "årsKarakter": 12, "prøveVægt": 1, "prøveKarakter": 12},
    5: {"n": 3,"fag": "Historie", "niveau": "A", "type": "", "årsVægt": 2, "årsKarakter": 7, "prøveVægt": 2, "prøveKarakter": 10},
    6: {"n": 3,"fag": "Matematik", "niveau": "A", "type": "mdt.", "årsVægt": 1, "årsKarakter": 12, "prøveVægt": 1, "prøveKarakter": 10},
    7: {"n": 3,"fag": "Matematik", "niveau": "A", "type": "skr.", "årsVægt": 1, "årsKarakter": 10, "prøveVægt": 1, "prøveKarakter": 12},
    8: {"n": 3,"fag": "Spansk begyndersprog", "niveau": "A", "type": "mdt.", "årsVægt": 1, "årsKarakter": 4, "prøveVægt": null, "prøveKarakter": null},
    9: {"n": 3,"fag": "Spansk begyndersprog", "niveau": "A", "type": "skr.", "årsVægt": 1, "årsKarakter": 7, "prøveVægt": 1, "prøveKarakter": 7},
    10: {"n": 2,"fag": "Engelsk", "niveau": "B", "type": "mdt.", "årsVægt": 0.75, "årsKarakter": 12, "prøveVægt": 0.75, "prøveKarakter": 7},
    11: {"n": 2,"fag": "Engelsk", "niveau": "B", "type": "skr.", "årsVægt": 0.75, "årsKarakter": 10, "prøveVægt": null, "prøveKarakter": null},
    12: {"n": 2,"fag": "Kemi", "niveau": "B", "type": "mdt.", "årsVægt": 0.75, "årsKarakter": 4, "prøveVægt": 1.5, "prøveKarakter": 2},
    13: {"n": 2,"fag": "Kemi", "niveau": "B", "type": "skr.", "årsVægt": 0.75, "årsKarakter": 4, "prøveVægt": null, "prøveKarakter": null},
    14: {"n": 1,"fag": "Idræt", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 2, "prøveVægt": null, "prøveKarakter": null},
    15: {"n": 1,"fag": "Informatik", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 12, "prøveVægt": null, "prøveKarakter": null},
    16: {"n": 1,"fag": "Mediefag", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 7, "prøveVægt": null, "prøveKarakter": null},
    17: {"n": 1,"fag": "Oltidskundskab", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 4, "prøveVægt": null, "prøveKarakter": null},
    18: {"n": 1,"fag": "Psykologi", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 4, "prøveVægt": null, "prøveKarakter": null},
    19: {"n": 1,"fag": "Religion", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 10, "prøveVægt": 1, "prøveKarakter": 7},
    20: {"n": 1,"fag": "Samfundsfag", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 7, "prøveVægt": 1, "prøveKarakter": 10},
    21: {"n": 0,"fag": "Almen sprogforståelse", "niveau": "", "type": "", "årsVægt": 0.25, "årsKarakter": 7, "prøveVægt": null, "prøveKarakter": null},
    22: {"n": 0,"fag": "Naturvidenskabeligt grundforløb", "niveau": "", "type": "", "årsVægt": 0.25, "årsKarakter": 10, "prøveVægt": null, "prøveKarakter": null},
    23: {"n": 0,"fag": "Studieretningsprojekt", "niveau": "", "type": "", "årsVægt": null, "årsKarakter": null, "prøveVægt": 2, "prøveKarakter": 10},
}