export const highSchoolDiplomaDict: {[key: number]: any} = {
    1: {"fag": "Dansk", "niveau": "A", "type": "mdt.", "årsVægt": 1, "årsKarakter": 7, "prøveVægt": null, "prøveKarakter": null},
    2: {"fag": "Dansk", "niveau": "A", "type": "skr.", "årsVægt": 1, "årsKarakter": 7, "prøveVægt": 1, "prøveKarakter": 7},
    3: {"fag": "Fysik", "niveau": "A", "type": "mdt.", "årsVægt": 1, "årsKarakter": 10, "prøveVægt": null, "prøveKarakter": null},
    4: {"fag": "Fysik", "niveau": "A", "type": "skr.", "årsVægt": 1, "årsKarakter": 12, "prøveVægt": 1, "prøveKarakter": 12},
    5: {"fag": "Historie", "niveau": "A", "type": "", "årsVægt": 2, "årsKarakter": 7, "prøveVægt": 2, "prøveKarakter": 10},
    6: {"fag": "Matematik", "niveau": "A", "type": "mdt.", "årsVægt": 1, "årsKarakter": 12, "prøveVægt": 1, "prøveKarakter": 10},
    7: {"fag": "Matematik", "niveau": "A", "type": "skr.", "årsVægt": 1, "årsKarakter": 10, "prøveVægt": 1, "prøveKarakter": 12},
    8: {"fag": "Spansk begyndersprog", "niveau": "A", "type": "mdt.", "årsVægt": 1, "årsKarakter": 4, "prøveVægt": null, "prøveKarakter": null},
    9: {"fag": "Spansk begyndersprog", "niveau": "A", "type": "skr.", "årsVægt": 1, "årsKarakter": 7, "prøveVægt": 1, "prøveKarakter": 7},
    10: {"fag": "Engelsk", "niveau": "B", "type": "mdt.", "årsVægt": 0.75, "årsKarakter": 12, "prøveVægt": 0.75, "prøveKarakter": 7},
    11: {"fag": "Engelsk", "niveau": "B", "type": "skr.", "årsVægt": 0.75, "årsKarakter": 10, "prøveVægt": null, "prøveKarakter": null},
    12: {"fag": "Kemi", "niveau": "B", "type": "mdt.", "årsVægt": 0.75, "årsKarakter": 4, "prøveVægt": 1.5, "prøveKarakter": 2},
    13: {"fag": "Kemi", "niveau": "B", "type": "skr.", "årsVægt": 0.75, "årsKarakter": 4, "prøveVægt": null, "prøveKarakter": null},
    14: {"fag": "Idræt", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 2, "prøveVægt": null, "prøveKarakter": null},
    15: {"fag": "Informatik", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 12, "prøveVægt": null, "prøveKarakter": null},
    16: {"fag": "Mediefag", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 7, "prøveVægt": null, "prøveKarakter": null},
    17: {"fag": "Oltidskundskab", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 4, "prøveVægt": null, "prøveKarakter": null},
    18: {"fag": "Psykologi", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 4, "prøveVægt": null, "prøveKarakter": null},
    19: {"fag": "Religion", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 10, "prøveVægt": 1, "prøveKarakter": 7},
    20: {"fag": "Samfundsfag", "niveau": "C", "type": "", "årsVægt": 1, "årsKarakter": 7, "prøveVægt": 1, "prøveKarakter": 10},
    21: {"fag": "Almen sprogforståelse", "niveau": "", "type": "", "årsVægt": 0.25, "årsKarakter": 7, "prøveVægt": null, "prøveKarakter": null},
    22: {"fag": "Naturvidenskabeligt grundforløb", "niveau": "", "type": "", "årsVægt": 0.25, "årsKarakter": 10, "prøveVægt": null, "prøveKarakter": null},
    23: {"fag": "Studieretningsprojekt", "niveau": "", "type": "", "årsVægt": null, "årsKarakter": null, "prøveVægt": 2, "prøveKarakter": 10},
}