import OpenAI from "openai";

const openai = new OpenAI({
  apiKey: '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',
  dangerouslyAllowBrowser: true
});

const content = `
This is a list of all the bachelor study programs at Aalborg University:

'Anvendt filosofi', city: 'Aalborg'
'Applied Industrial Electronics', city: 'Esbjerg'
'Arkitektur og design', city: 'Aalborg'
'Biologi', city: 'Aalborg'
'Bioteknologi', city: 'Aalborg'
'By-, energi- og miljøplanlægning', city: 'København'
'By-, energi- og miljøplanlægning', city: 'Aalborg'
'Byggeri og anlæg', city: 'Aalborg'
'Byggeri og anlæg, Diplomingeniør', city: 'Aalborg'
'Byggeri og anlæg, Diplomingeniør', city: 'Esbjerg'
'Bæredygtig energiteknik, diplomingeniør', city: 'Esbjerg'
'Bæredygtig energiteknik, diplomingeniør', city: 'Aalborg'
'Bæredygtige byggeprocesser', city: 'København'
'Bæredygtigt design', city: 'København'
'Chemical Engineering and Biotechnology', city: 'Esbjerg'
'Computerteknologi', city: 'Aalborg'
'Cyber- og computerteknologi', city: 'København'
'Dansk', city: 'Aalborg'
'Datalogi', city: 'Aalborg'
'Datavidenskab og machine learning', city: 'Aalborg'
'Design og anvendelse af kunstig intelligens', city: 'Aalborg'
'Economics and Business Administration', city: 'Aalborg'
'Elektronik og systemdesign', city: 'Aalborg'
'Elektronik, Diplomingeniør', city: 'Aalborg'
'Energi', city: 'Esbjerg'
'Energi', city: 'Aalborg'
'Engelsk', city: 'Aalborg'
'Erhvervsøkonomi (HA)', city: 'Aalborg'
'Erhvervsøkonomi-jura HA (jur.)', city: 'Aalborg'
'Fysik', city: 'Aalborg'
'Fysik og teknologi (tidl. Nanoteknologi)', city: 'Aalborg'
'Geografi', city: 'Aalborg'
'Globale Forretningssystemer', city: 'Aalborg'
'Globale Forretningssystemer, Diplomingeniør', city: 'Aalborg'
'Historie', city: 'Aalborg'
'Idræt', city: 'Aalborg'
'Informationsteknologi', city: 'Aalborg'
'Ingeniørvidenskab', city: 'Aalborg'
'Innovation og digitalisering', city: 'Aalborg'
'Interaktionsdesign', city: 'Aalborg'
'International Virksomhedskommunikation i Engelsk', city: 'Aalborg'
'Jura', city: 'Aalborg'
'Kemi', city: 'Aalborg'
'Kemi og bioteknologi, Diplomingeniør', city: 'Esbjerg'
'Kemi og bioteknologi, Diplomingeniør', city: 'Aalborg'
'Kemiteknologi', city: 'Aalborg'
'Kommunikation og digitale medier', city: 'Aalborg'
'Kunst og teknologi', city: 'Aalborg'
'Landinspektørvidenskab', city: 'København'
'Landinspektørvidenskab', city: 'Aalborg'
'Maskinteknik, Diplomingeniør', city: 'Aalborg'
'Maskinteknik, Diplomingeniør', city: 'Esbjerg'
'Matematik', city: 'Aalborg'
'Matematik-teknologi', city: 'Aalborg'
'Matematik-økonomi', city: 'Aalborg'
'Medialogi', city: 'Aalborg'
'Medialogi', city: 'København'
'Medicin (Lægeuddannelsen)', city: 'Aalborg'
'Medicin med industriel specialisering', city: 'Aalborg'
'Mekanik og produktion', city: 'Aalborg'
'Miljøvidenskab', city: 'Aalborg'
'Musik', city: 'Aalborg'
'Musikterapi', city: 'Aalborg'
'Organisatorisk læring', city: 'Aalborg'
'Politik og administration', city: 'Aalborg'
'Psykologi', city: 'Aalborg'
'Robotteknologi', city: 'Aalborg'
'Samfundsfag', city: 'Aalborg'
'Socialrådgiver', city: 'Aalborg'
'Sociologi', city: 'Aalborg'
'Software', city: 'København'
'Software', city: 'Aalborg'
'Sprog og internationale studier, engelsk', city: 'Aalborg'
'Sundhedsteknologi', city: 'Aalborg'
'Teknoantropologi', city: 'Aalborg'
'Økonomi', city: 'Aalborg'

This is a list of all the masters study programs at Aalborg University:

'Advanced Power Electronics', city: 'Esbjerg'
'Anvendt filosofi', city: 'Aalborg'
'Architecture, Civilingeniør', city: 'Aalborg'
'Bioengineering, Civilingeniør', city: 'Esbjerg'
'Biologi', city: 'Aalborg'
'Biotechnology, Civilingeniør', city: 'Aalborg'
'Building Energy Design, Cand.tech.', city: 'Aalborg'
'Byggeledelse og bygningsinformatik', city: 'Aalborg'
'Byggeledelse, Civilingeniør', city: 'Aalborg'
'Chemical Engineering, Civilingeniør', city: 'Esbjerg'
'Chemistry, Civilingeniør', city: 'Aalborg'
'Computer Engineering, Civilingeniør', city: 'Aalborg'
'Computer science (IT)', city: 'Aalborg'
'Culture, Communication and Globalization', city: 'Aalborg'
'Cyber Security, Civilingeniør', city: 'København'
'Dansk', city: 'Aalborg'
'Datalogi', city: 'Aalborg'
'Datavidenskab og machine learning', city: 'Aalborg'
'Digitalisering og applikationsudvikling', city: 'Aalborg'
'Economics and Business Administration', city: 'Aalborg'
'Electronic Systems, Civilingeniør', city: 'Aalborg'
'Energy Engineering, Civilingeniør', city: 'Aalborg'
'Engelsk', city: 'Aalborg'
'Entrepreneurial Business Engineering', city: 'Aalborg'
'Erhvervsøkonomi', city: 'Aalborg'
'Erhvervsøkonomi-jura', city: 'Aalborg'
'Folkesundhedsvidenskab', city: 'Aalborg'
'Fysik', city: 'Aalborg'
'Geography', city: 'Aalborg' 
'Historie', city: 'Aalborg'
'Idræt', city: 'Aalborg'
'Indoor Environmental and Energy Engineering, Civilingeniør', city: 'Aalborg'
'Industrial Design, Civilingeniør', city: 'Aalborg'
'Information Studies (Human Centered Informatics)', city: 'København'
'Informationsvidenskab', city: 'Aalborg'
'Innovative Communication Technologies and Entrepreneurship, Civilingeniør', city: 'København'
'Intelligent Reliable Systems, Civilingeniør', city: 'Esbjerg'
'Interaktionsdesign', city: 'Aalborg'
'Interaktive digitale medier', city: 'Aalborg'
'International Relations', city: 'Aalborg'
'International Virksomhedskommunikation i Engelsk', city: 'Aalborg'
'It, læring og organisatorisk omstilling', city: 'København'
'It, læring og organisatorisk omstilling', city: 'Aalborg'
'It-ledelse', city: 'Aalborg'
'Jura', city: 'Aalborg'
'Kemi', city: 'Aalborg'
'Klinisk videnskab og teknologi', city: 'Aalborg'
'Kommunikation', city: 'København'
 'Kommunikation', city: 'Aalborg'
'Kriminologi', city: 'Aalborg'
'Ledelse og informatik i byggeriet, Cand.tech.', city: 'København'
'Lighting Design, Cand.scient.', city: 'København'
'Læring og forandringsprocesser', city: 'Aalborg'
'Læring og forandringsprocesser', city: 'København'
'Management Engineering', city: 'Aalborg'
'Matematik', city: 'Aalborg'
'Matematik-teknologi', city: 'Aalborg'
'Matematik-økonomi', city: 'Aalborg'
'Mechanical Engineering, Civilingeniør', city: 'Aalborg'
'Medialogy', city: 'København'
'Medialogy', city: 'Aalborg'
'Medicin (Lægevidenskab)', city: 'Aalborg'
'Medicine with Industrial Specialisation', city: 'Aalborg'
'Musik', city: 'Aalborg'
'Musikterapi', city: 'Aalborg'
'Muskuloskeletal fysioterapi', city: 'Aalborg'
'Oplevelsesdesign', city: 'Aalborg'
'Physics and Technology, Civilingeniør', city: 'Aalborg'
'Politik og administration', city: 'Aalborg'
'Produkt- og Designpsykologi, Civilingeniør', city: 'Aalborg'
'Psykologi', city: 'Aalborg'
'Revision', city: 'Aalborg'
'Risk and Safety Management', city: 'Esbjerg'
'Robotics', city: 'Aalborg'
'Samfundsfag', city: 'Aalborg'
'Service Systems Design', city: 'København'
'Socialt arbejde', city: 'København'
'Socialt arbejde', city: 'Aalborg'
'Sociologi', city: 'Aalborg'
'Software, Civilingeniør', city: 'København'
'Software, Civilingeniør', city: 'Aalborg'
'Sound and Music Computing, Civilingeniør', city: 'København'
'Structural and Civil Engineering, Civilingeniør', city: 'Aalborg'
'Sundhedsteknologi', city: 'Aalborg'
'Surveying, Planning and Land Management', city: 'København'
'Surveying, Planning and Land Management', city: 'Aalborg'
'Sustainable Biotechnology', city: 'København'
'Sustainable Cities, Civilingeniør', city: 'København'
'Sustainable Design, Civilingeniør', city: 'København'
'Sustainable Energy Engineering, Civilingeniør', city: 'Esbjerg'
'Techno-Anthropology', city: 'København'
'Techno-Anthropology', city: 'Aalborg'
'Tourism', city: 'Aalborg'
'Tysk', city: 'Aalborg'
'Urban Design, Cand.tech.', city: 'Aalborg'
'Urban Design, Civilingeniør', city: 'Aalborg'
'Urban, Energy and Environmental Planning', city: 'Aalborg'
'Veje og trafik', city: 'Aalborg'
'Visual Studies and Art Education', city: 'København'
'Water and Environmental Engineering, Civilingeniør', city: 'Aalborg'
'Økonomi', city: 'Aalborg'

The user will give you the title or a description of their dream job, 
and you will answer with the study program that is closest to that job or job description and in what city the department is at

You will only answer with suggestions for study programs that are a part of the lists

You will not ask any followup questions

You will always answer in Danish

You will never repeat the users input
`;

export async function OpenAIchat(prompt) {
  const completion = await openai.chat.completions.create({
    messages: [
      { role: "user", content: prompt },
      { role: "assistant", content: content,}
    ],
    model: "gpt-3.5-turbo",
  });

  const assistantReply = completion.choices[0].message.content;
  return assistantReply;
}